
/*
 * 
 */

package ar.edu.utn.frba.tacs.mercadowarnessh.facturacion;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.1
 * Mon Jun 14 00:08:42 ART 2010
 * Generated source version: 2.2.1
 * 
 */


@WebServiceClient(name = "PedidosServiceImplService", 
                  wsdlLocation = "http://127.0.0.1:8080/WarnesSimulator/PedidosService?wsdl",
                  targetNamespace = "http://facturacion.mercadowarnessh.tacs.frba.utn.edu.ar/") 
public class PedidosServiceImplService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://facturacion.mercadowarnessh.tacs.frba.utn.edu.ar/", "PedidosServiceImplService");
    public final static QName PedidosServiceImplPort = new QName("http://facturacion.mercadowarnessh.tacs.frba.utn.edu.ar/", "PedidosServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:8080/WarnesSimulator/PedidosService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://127.0.0.1:8080/WarnesSimulator/PedidosService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public PedidosServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PedidosServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PedidosServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns PedidosService
     */
    @WebEndpoint(name = "PedidosServiceImplPort")
    public PedidosService getPedidosServiceImplPort() {
        return super.getPort(PedidosServiceImplPort, PedidosService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PedidosService
     */
    @WebEndpoint(name = "PedidosServiceImplPort")
    public PedidosService getPedidosServiceImplPort(WebServiceFeature... features) {
        return super.getPort(PedidosServiceImplPort, PedidosService.class, features);
    }

}
